/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.Administrador;
import Model.AdministradorDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author karin
 */
public class crearAdministrador extends javax.swing.JDialog {
    private int idAdministradorCreado = -1;
    /**
     * Creates new form crearAdministrador
     */
    
    public int getIdAdministradorCreado() {
        return idAdministradorCreado;
    }
    
    public crearAdministrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        nombreAdministradorCATextField = new javax.swing.JTextField();
        apellidoAdministradorCATextField = new javax.swing.JTextField();
        correoAdministradorCATextField = new javax.swing.JTextField();
        fechaNacimientoAdministradorCATextField = new javax.swing.JTextField();
        edadAdministradorCATextField = new javax.swing.JTextField();
        DMid_Membresia = new javax.swing.JLabel();
        DMid_Membresia1 = new javax.swing.JLabel();
        DMid_Membresia2 = new javax.swing.JLabel();
        DMid_Membresia3 = new javax.swing.JLabel();
        DMid_Membresia4 = new javax.swing.JLabel();
        crearCAButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 255, 205));

        jPanel2.setBackground(new java.awt.Color(247, 255, 205));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo Administrador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        jPanel3.setBackground(new java.awt.Color(222, 235, 181));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Información"));

        nombreAdministradorCATextField.setForeground(new java.awt.Color(153, 153, 153));
        nombreAdministradorCATextField.setText("Nombre");
        nombreAdministradorCATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAdministradorCATextFieldActionPerformed(evt);
            }
        });

        apellidoAdministradorCATextField.setForeground(new java.awt.Color(153, 153, 153));
        apellidoAdministradorCATextField.setText("Apellido");
        apellidoAdministradorCATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoAdministradorCATextFieldActionPerformed(evt);
            }
        });

        correoAdministradorCATextField.setForeground(new java.awt.Color(153, 153, 153));
        correoAdministradorCATextField.setText("Correo");
        correoAdministradorCATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoAdministradorCATextFieldActionPerformed(evt);
            }
        });

        fechaNacimientoAdministradorCATextField.setForeground(new java.awt.Color(153, 153, 153));
        fechaNacimientoAdministradorCATextField.setText("Fecha nacimiento");
        fechaNacimientoAdministradorCATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaNacimientoAdministradorCATextFieldActionPerformed(evt);
            }
        });

        edadAdministradorCATextField.setForeground(new java.awt.Color(153, 153, 153));
        edadAdministradorCATextField.setText("Edad");
        edadAdministradorCATextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadAdministradorCATextFieldActionPerformed(evt);
            }
        });

        DMid_Membresia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMid_Membresia.setText("Apellido:");

        DMid_Membresia1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMid_Membresia1.setText("Nombre:");

        DMid_Membresia2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMid_Membresia2.setText("Correo:");

        DMid_Membresia3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMid_Membresia3.setText("Fecha Nacimiento:");

        DMid_Membresia4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMid_Membresia4.setText("Edad:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DMid_Membresia1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(edadAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaNacimientoAdministradorCATextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreAdministradorCATextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoAdministradorCATextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(DMid_Membresia2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(correoAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DMid_Membresia, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DMid_Membresia4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DMid_Membresia3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DMid_Membresia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DMid_Membresia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DMid_Membresia2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaNacimientoAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DMid_Membresia3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadAdministradorCATextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DMid_Membresia4))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        crearCAButton.setBackground(new java.awt.Color(222, 235, 181));
        crearCAButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        crearCAButton.setText("Crear");
        crearCAButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        crearCAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCAButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(crearCAButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crearCAButton)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreAdministradorCATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAdministradorCATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAdministradorCATextFieldActionPerformed

    private void apellidoAdministradorCATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoAdministradorCATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoAdministradorCATextFieldActionPerformed

    private void correoAdministradorCATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoAdministradorCATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoAdministradorCATextFieldActionPerformed

    private void fechaNacimientoAdministradorCATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaNacimientoAdministradorCATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaNacimientoAdministradorCATextFieldActionPerformed

    private void edadAdministradorCATextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadAdministradorCATextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadAdministradorCATextFieldActionPerformed

    private void crearCAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCAButtonActionPerformed
        // TODO add your handling code here:
        try {
            String nombre = nombreAdministradorCATextField.getText().trim();
            String apellido = apellidoAdministradorCATextField.getText().trim();
            String correo = correoAdministradorCATextField.getText().trim();
            String fechaNacimiento = fechaNacimientoAdministradorCATextField.getText().trim();
            int edad = Integer.parseInt(edadAdministradorCATextField.getText().trim());

            if (nombre.isEmpty() || apellido.isEmpty() || correo.isEmpty() || fechaNacimiento.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, llena todos los campos", "Campos incompletos", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Administrador nuevoAdmin = new Administrador();
            nuevoAdmin.setNombre(nombre);
            nuevoAdmin.setApellido(apellido);
            nuevoAdmin.setCorreo(correo);
            nuevoAdmin.setFechaNacimiento(fechaNacimiento);
            nuevoAdmin.setEdad(edad);

            AdministradorDAO dao = new AdministradorDAO();
            int idGenerado = dao.insertarAdministrador(nuevoAdmin);

            if (idGenerado != -1) {
                this.idAdministradorCreado = idGenerado;
                JOptionPane.showMessageDialog(this, "Administrador creado exitosamente");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo crear el administrador", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Edad inválida", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al crear administrador:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_crearCAButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                crearAdministrador dialog = new crearAdministrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DMid_Membresia;
    private javax.swing.JLabel DMid_Membresia1;
    private javax.swing.JLabel DMid_Membresia2;
    private javax.swing.JLabel DMid_Membresia3;
    private javax.swing.JLabel DMid_Membresia4;
    private javax.swing.JTextField apellidoAdministradorCATextField;
    private javax.swing.JTextField correoAdministradorCATextField;
    private javax.swing.JButton crearCAButton;
    private javax.swing.JTextField edadAdministradorCATextField;
    private javax.swing.JTextField fechaNacimientoAdministradorCATextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombreAdministradorCATextField;
    // End of variables declaration//GEN-END:variables
}
