/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Model.Administrador;
import Model.Membresia;
import Model.Ubicacion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karin
 */
public class DetallesMembresia extends javax.swing.JDialog {

    private DefaultTableModel modeloTablaAdmin;
    private DefaultTableModel modeloTablaUbicacion;
    
    /**
     * Creates new form DetallesMembresia
     */
    public DetallesMembresia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Hacer los campos de texto no editables
        idMembresíaDMTextField.setEditable(false);
        limiteDMTextField.setEditable(false);
        fechaInicioDMTextField.setEditable(false);
        duracionDMTextField1.setEditable(false);
        idAdministradorDMTextField1.setEditable(false);
        idUbicacionDMTextField1.setEditable(false);

        
        // Inicializar modelo de la tabla de Administradores
        modeloTablaAdmin = new DefaultTableModel(
            new Object[]{"Nombre", "Apellido", "Correo", "Nacimiento", "Edad"}, 0);
        tablaAdministrador.setModel(modeloTablaAdmin);

        // Inicializar modelo de la tabla de Ubicación
        modeloTablaUbicacion = new DefaultTableModel(
            new Object[]{"ID", "País", "Ciudad"}, 0);
        tablaUbicacion.setModel(modeloTablaUbicacion);
    }
    
    public void setDatosMembresia(Membresia m) {
        idMembresíaDMTextField.setText(String.valueOf(m.getIdMembresia()));
        limiteDMTextField.setText(String.valueOf(m.getLimite()));
        fechaInicioDMTextField.setText(String.valueOf(m.getFechaInicio()));
        duracionDMTextField1.setText(String.valueOf(m.getDuracion()));
        idAdministradorDMTextField1.setText(String.valueOf(m.getIdAdministrador()));
        idUbicacionDMTextField1.setText(String.valueOf(m.getIdUbicacion()));
    }

    public void setDatosAdministrador(Administrador a) {
        modeloTablaAdmin.setRowCount(0);
        if (a != null){
            modeloTablaAdmin.addRow(new Object[]{
                a.getNombre(),
                a.getApellido(),
                a.getCorreo(),
                a.getFechaNacimiento(),
                a.getEdad()
            });
        } else {
            modeloTablaAdmin.addRow(new Object[]{"No disponible", "No disponible", "No disponible", "N/A", "N/A"});
        }
    }

    public void setDatosUbicacion(Ubicacion u) {
        modeloTablaUbicacion.setRowCount(0);
        if (u != null) {
            modeloTablaUbicacion.addRow(new Object[]{
                u.getIdUbicacion(),
                u.getPais(),
                u.getCiudad()
            });
        } else {
            modeloTablaUbicacion.addRow(new Object[]{"N/A", "No disponible", "No disponible"});
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        panelMembresiasDM = new javax.swing.JPanel();
        fechaInicioDM = new javax.swing.JLabel();
        DMid_Membresia = new javax.swing.JLabel();
        idMembresíaDMTextField = new javax.swing.JTextField();
        limiteDMTextField = new javax.swing.JTextField();
        fechaInicioDMTextField = new javax.swing.JTextField();
        limiteDM = new javax.swing.JLabel();
        duraciónDM = new javax.swing.JLabel();
        duracionDMTextField1 = new javax.swing.JTextField();
        idAdministradorDMTextField1 = new javax.swing.JTextField();
        idAdministradorDM = new javax.swing.JLabel();
        idUbicacionDMTextField1 = new javax.swing.JTextField();
        idUbicacionDM = new javax.swing.JLabel();
        panelTituloDM = new javax.swing.JPanel();
        detallesMembresías = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        panelAdministrador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAdministrador = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        panelUbicacion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUbicacion = new javax.swing.JTable();
        cerrarDMButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 255, 205));

        panelMembresiasDM.setBackground(new java.awt.Color(222, 235, 181));
        panelMembresiasDM.setBorder(javax.swing.BorderFactory.createTitledBorder("Membresía"));

        fechaInicioDM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fechaInicioDM.setText("Fecha inicio:");

        DMid_Membresia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        DMid_Membresia.setText("ID Membresía:");

        idMembresíaDMTextField.setForeground(new java.awt.Color(153, 153, 153));
        idMembresíaDMTextField.setText("ID Membresía");
        idMembresíaDMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMembresíaDMTextFieldActionPerformed(evt);
            }
        });

        limiteDMTextField.setForeground(new java.awt.Color(153, 153, 153));
        limiteDMTextField.setText("Limite");
        limiteDMTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limiteDMTextFieldActionPerformed(evt);
            }
        });

        fechaInicioDMTextField.setForeground(new java.awt.Color(153, 153, 153));
        fechaInicioDMTextField.setText("Fecha inicio");

        limiteDM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        limiteDM.setText("Limite:");

        duraciónDM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        duraciónDM.setText("Duración:");

        duracionDMTextField1.setForeground(new java.awt.Color(153, 153, 153));
        duracionDMTextField1.setText("Duración");
        duracionDMTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionDMTextField1ActionPerformed(evt);
            }
        });

        idAdministradorDMTextField1.setForeground(new java.awt.Color(153, 153, 153));
        idAdministradorDMTextField1.setText("ID Administrador");
        idAdministradorDMTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAdministradorDMTextField1ActionPerformed(evt);
            }
        });

        idAdministradorDM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        idAdministradorDM.setText("ID Administrador:");

        idUbicacionDMTextField1.setForeground(new java.awt.Color(153, 153, 153));
        idUbicacionDMTextField1.setText("ID Ubicación");

        idUbicacionDM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        idUbicacionDM.setText("ID Ubicación:");

        javax.swing.GroupLayout panelMembresiasDMLayout = new javax.swing.GroupLayout(panelMembresiasDM);
        panelMembresiasDM.setLayout(panelMembresiasDMLayout);
        panelMembresiasDMLayout.setHorizontalGroup(
            panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembresiasDMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMembresiasDMLayout.createSequentialGroup()
                        .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DMid_Membresia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limiteDM)
                            .addComponent(fechaInicioDM)
                            .addComponent(duraciónDM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idAdministradorDM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idAdministradorDMTextField1)
                            .addComponent(duracionDMTextField1)
                            .addComponent(idMembresíaDMTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(limiteDMTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fechaInicioDMTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMembresiasDMLayout.createSequentialGroup()
                        .addComponent(idUbicacionDM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idUbicacionDMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelMembresiasDMLayout.setVerticalGroup(
            panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMembresiasDMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DMid_Membresia)
                    .addComponent(idMembresíaDMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limiteDMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limiteDM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaInicioDMTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaInicioDM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duraciónDM)
                    .addComponent(duracionDMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idAdministradorDMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idAdministradorDM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMembresiasDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUbicacionDMTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idUbicacionDM))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTituloDM.setBackground(new java.awt.Color(247, 255, 205));

        detallesMembresías.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        detallesMembresías.setText("Detalles Membresías");
        detallesMembresías.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout panelTituloDMLayout = new javax.swing.GroupLayout(panelTituloDM);
        panelTituloDM.setLayout(panelTituloDMLayout);
        panelTituloDMLayout.setHorizontalGroup(
            panelTituloDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloDMLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detallesMembresías)
                .addGap(136, 136, 136))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panelTituloDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTituloDMLayout.createSequentialGroup()
                    .addGap(0, 91, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 258, Short.MAX_VALUE)))
        );
        panelTituloDMLayout.setVerticalGroup(
            panelTituloDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloDMLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(detallesMembresías)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTituloDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelTituloDMLayout.createSequentialGroup()
                    .addGap(0, 21, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
        );

        panelAdministrador.setBackground(new java.awt.Color(222, 235, 181));
        panelAdministrador.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrador"));

        tablaAdministrador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Correo", "Nacimiento ", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAdministrador);

        javax.swing.GroupLayout panelAdministradorLayout = new javax.swing.GroupLayout(panelAdministrador);
        panelAdministrador.setLayout(panelAdministradorLayout);
        panelAdministradorLayout.setHorizontalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAdministradorLayout.setVerticalGroup(
            panelAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdministradorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelUbicacion.setBackground(new java.awt.Color(222, 235, 181));
        panelUbicacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Ubicación"));

        tablaUbicacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID Ubicación", "País", "Ciudad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaUbicacion);

        javax.swing.GroupLayout panelUbicacionLayout = new javax.swing.GroupLayout(panelUbicacion);
        panelUbicacion.setLayout(panelUbicacionLayout);
        panelUbicacionLayout.setHorizontalGroup(
            panelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelUbicacionLayout.setVerticalGroup(
            panelUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cerrarDMButton.setBackground(new java.awt.Color(222, 235, 181));
        cerrarDMButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cerrarDMButton.setText("Salir");
        cerrarDMButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cerrarDMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarDMButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTituloDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelMembresiasDM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(panelAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(panelUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarDMButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelTituloDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMembresiasDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrarDMButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idMembresíaDMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMembresíaDMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMembresíaDMTextFieldActionPerformed

    private void limiteDMTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limiteDMTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limiteDMTextFieldActionPerformed

    private void duracionDMTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionDMTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionDMTextField1ActionPerformed

    private void idAdministradorDMTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAdministradorDMTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAdministradorDMTextField1ActionPerformed

    private void cerrarDMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarDMButtonActionPerformed
        // TODO add your handling code here:
        cerrarDMButton.addActionListener(e -> this.dispose());
    }//GEN-LAST:event_cerrarDMButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesMembresia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesMembresia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesMembresia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesMembresia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesMembresia dialog = new DetallesMembresia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DMid_Membresia;
    private javax.swing.JButton cerrarDMButton;
    private javax.swing.JLabel detallesMembresías;
    private javax.swing.JTextField duracionDMTextField1;
    private javax.swing.JLabel duraciónDM;
    private javax.swing.JLabel fechaInicioDM;
    private javax.swing.JTextField fechaInicioDMTextField;
    private javax.swing.JLabel idAdministradorDM;
    private javax.swing.JTextField idAdministradorDMTextField1;
    private javax.swing.JTextField idMembresíaDMTextField;
    private javax.swing.JLabel idUbicacionDM;
    private javax.swing.JTextField idUbicacionDMTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel limiteDM;
    private javax.swing.JTextField limiteDMTextField;
    private javax.swing.JPanel panelAdministrador;
    private javax.swing.JPanel panelMembresiasDM;
    private javax.swing.JPanel panelTituloDM;
    private javax.swing.JPanel panelUbicacion;
    private javax.swing.JTable tablaAdministrador;
    private javax.swing.JTable tablaUbicacion;
    // End of variables declaration//GEN-END:variables
}
