/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.controllerPerfil;
import Model.GustaDe;
import Model.Historial;
import Model.Perfil;
import Model.Recomendacion;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karin
 */
public class DetallesPerfil extends javax.swing.JDialog {
    
    private controllerPerfil controller;
    private DefaultTableModel modeloTablaHistorial;
    private DefaultTableModel modeloTablaGustos;
    private DefaultTableModel modeloTablaRecomendaciones;

    /**
     * Creates new form DetallesPerfil
     */
    public DetallesPerfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(getParent());
        
        // Hacer los campos de texto no editables
        idPerfilTextFieldDP.setEditable(false);
        nickNameTextFieldDP.setEditable(true);
        idMembresiaTextFieldDP.setEditable(false);
        
        // Inicializar modelo de la tabla de historial
        modeloTablaHistorial = new DefaultTableModel(
            new Object[]{"ID historial", "Fecha", "Contenido"}, 0);
        tablaHistorial.setModel(modeloTablaHistorial);

        // Inicializar modelo de la tabla de gustos
        modeloTablaGustos = new DefaultTableModel(
            new Object[]{"Estilo", "Frecuencia", "Nivel Gusto"}, 0);
        tablaGustos.setModel(modeloTablaGustos);
        
        // Inicializar modelo de la tabla de recomendaciones
        modeloTablaRecomendaciones = new DefaultTableModel(
            new Object[]{"ID recomendación", "Fecha", "Nombre Estilo", "ID Estilo"}, 0);
        tablaRecomendaciones.setModel(modeloTablaRecomendaciones);
    }

    public void setDatosPerfil(Perfil p) {
        idPerfilTextFieldDP.setText(String.valueOf(p.getId_perfil()));
        nickNameTextFieldDP.setText(String.valueOf(p.getNickName()));
        idMembresiaTextFieldDP.setText(String.valueOf(p.getId_membresia()));
    }

    public void setDatosHistorial(List<Historial> hist) {
        modeloTablaHistorial.setRowCount(0);
        if (hist != null && !hist.isEmpty()){
            for (Historial h : hist){
                modeloTablaHistorial.addRow(new Object[]{
                    h.getIdHistorial(),
                    h.getFecha(),
                    h.getDescripcion()
                });
            }
        } else {
            modeloTablaHistorial.addRow(new Object[]{"No disponible", "No disponible", "No disponible"});
        }
    }

    public void setDatosGustos(List<GustaDe> gustos) {
        modeloTablaGustos.setRowCount(0);
        if (gustos != null && !gustos.isEmpty()) {
            for(GustaDe g : gustos){
                modeloTablaGustos.addRow(new Object[]{
                    g.getNombreEstilo(),
                    g.getFrecuencia(),
                    g.getNivelGusto()
                });
            }
        } else {
            modeloTablaGustos.addRow(new Object[]{"No disponible", "No disponible", "No disponible"});
        }
    }
    
    public void setDatosRecomendacion(List<Recomendacion> recom) {
        modeloTablaRecomendaciones.setRowCount(0);
        if (recom != null && !recom.isEmpty()) {
            for (Recomendacion r : recom){
                modeloTablaRecomendaciones.addRow(new Object[]{
                    r.getId_recomendacion(),
                    r.getFecha(),
                    r.getNombreEstilo(),
                    r.getId_estilo()
                });
            }
        } else {
            modeloTablaRecomendaciones.addRow(new Object[]{"No disponible", "No disponible", "No disponible", "No disponible"});
        }
    }
    
    private void actualizarPerfil() {
        try {
            Perfil p = new Perfil(
                Integer.parseInt(idPerfilTextFieldDP.getText()),
                nickNameTextFieldDP.getText(),
                Integer.parseInt(idMembresiaTextFieldDP.getText())
            );
            if (controller.actualizarPerfil(p)) {
                JOptionPane.showMessageDialog(this, "Perfil actualizado");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifica los campos numéricos");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        panelTituloDP = new javax.swing.JPanel();
        detallesPerfil = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelPerfilDP = new javax.swing.JPanel();
        id_PerfilDP = new javax.swing.JLabel();
        idPerfilTextFieldDP = new javax.swing.JTextField();
        nickNameTextFieldDP = new javax.swing.JTextField();
        idMembresiaTextFieldDP = new javax.swing.JTextField();
        nicknameDP = new javax.swing.JLabel();
        id_membresiaDP = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        panelHistorial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        panelGustos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaGustos = new javax.swing.JTable();
        jSeparator4 = new javax.swing.JSeparator();
        panelRecomendaciones = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaRecomendaciones = new javax.swing.JTable();
        salirDPButton = new javax.swing.JButton();
        actualizarDPButton = new javax.swing.JButton();

        jScrollPane3.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 255, 205));

        panelTituloDP.setBackground(new java.awt.Color(247, 255, 205));

        detallesPerfil.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        detallesPerfil.setText("Detalles Perfil");
        detallesPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout panelTituloDPLayout = new javax.swing.GroupLayout(panelTituloDP);
        panelTituloDP.setLayout(panelTituloDPLayout);
        panelTituloDPLayout.setHorizontalGroup(
            panelTituloDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloDPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detallesPerfil)
                .addGap(164, 164, 164))
        );
        panelTituloDPLayout.setVerticalGroup(
            panelTituloDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloDPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detallesPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPerfilDP.setBackground(new java.awt.Color(222, 235, 181));
        panelPerfilDP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(146, 176, 109))); // NOI18N

        id_PerfilDP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_PerfilDP.setText("ID Perfil:");

        idPerfilTextFieldDP.setForeground(new java.awt.Color(153, 153, 153));
        idPerfilTextFieldDP.setText("ID Perfil");
        idPerfilTextFieldDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPerfilTextFieldDPActionPerformed(evt);
            }
        });

        nickNameTextFieldDP.setForeground(new java.awt.Color(153, 153, 153));
        nickNameTextFieldDP.setText("Nickname");
        nickNameTextFieldDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickNameTextFieldDPActionPerformed(evt);
            }
        });

        idMembresiaTextFieldDP.setForeground(new java.awt.Color(153, 153, 153));
        idMembresiaTextFieldDP.setText("ID Membresía");

        nicknameDP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nicknameDP.setText("Nickname:");

        id_membresiaDP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_membresiaDP.setText("ID Membresía:");

        javax.swing.GroupLayout panelPerfilDPLayout = new javax.swing.GroupLayout(panelPerfilDP);
        panelPerfilDP.setLayout(panelPerfilDPLayout);
        panelPerfilDPLayout.setHorizontalGroup(
            panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilDPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_PerfilDP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameDP)
                    .addComponent(id_membresiaDP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(idPerfilTextFieldDP)
                    .addComponent(nickNameTextFieldDP)
                    .addComponent(idMembresiaTextFieldDP, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPerfilDPLayout.setVerticalGroup(
            panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilDPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_PerfilDP)
                    .addComponent(idPerfilTextFieldDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nickNameTextFieldDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nicknameDP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerfilDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idMembresiaTextFieldDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_membresiaDP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelHistorial.setBackground(new java.awt.Color(222, 235, 181));
        panelHistorial.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial"));

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID historial", "Fecha", "Contenido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaHistorial);
        if (tablaHistorial.getColumnModel().getColumnCount() > 0) {
            tablaHistorial.getColumnModel().getColumn(0).setResizable(false);
            tablaHistorial.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout panelHistorialLayout = new javax.swing.GroupLayout(panelHistorial);
        panelHistorial.setLayout(panelHistorialLayout);
        panelHistorialLayout.setHorizontalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelHistorialLayout.setVerticalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        panelGustos.setBackground(new java.awt.Color(222, 235, 181));
        panelGustos.setBorder(javax.swing.BorderFactory.createTitledBorder("Gustos"));

        tablaGustos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Estilo", "Frecuencia", "Nivel Gusto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaGustos);

        javax.swing.GroupLayout panelGustosLayout = new javax.swing.GroupLayout(panelGustos);
        panelGustos.setLayout(panelGustosLayout);
        panelGustosLayout.setHorizontalGroup(
            panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGustosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panelGustosLayout.setVerticalGroup(
            panelGustosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGustosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        panelRecomendaciones.setBackground(new java.awt.Color(222, 235, 181));
        panelRecomendaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Recomendaciones"));

        tablaRecomendaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID recomendación", "Fecha", "Nombre Estilo", "ID estilo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaRecomendaciones);

        javax.swing.GroupLayout panelRecomendacionesLayout = new javax.swing.GroupLayout(panelRecomendaciones);
        panelRecomendaciones.setLayout(panelRecomendacionesLayout);
        panelRecomendacionesLayout.setHorizontalGroup(
            panelRecomendacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecomendacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        panelRecomendacionesLayout.setVerticalGroup(
            panelRecomendacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecomendacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329))
        );

        salirDPButton.setBackground(new java.awt.Color(222, 235, 181));
        salirDPButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        salirDPButton.setText("Salir");
        salirDPButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salirDPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirDPButtonActionPerformed(evt);
            }
        });

        actualizarDPButton.setBackground(new java.awt.Color(222, 235, 181));
        actualizarDPButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        actualizarDPButton.setText("Actualizar");
        actualizarDPButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        actualizarDPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarDPButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTituloDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPerfilDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2)
                    .addComponent(panelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(panelGustos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(panelRecomendaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(actualizarDPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salirDPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelTituloDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPerfilDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salirDPButton)
                            .addComponent(actualizarDPButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelGustos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRecomendaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idPerfilTextFieldDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPerfilTextFieldDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPerfilTextFieldDPActionPerformed

    private void nickNameTextFieldDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickNameTextFieldDPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickNameTextFieldDPActionPerformed

    private void salirDPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirDPButtonActionPerformed
        // TODO add your handling code here:
        salirDPButton.addActionListener(e -> this.dispose());
    }//GEN-LAST:event_salirDPButtonActionPerformed

    private void actualizarDPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarDPButtonActionPerformed
        // TODO add your handling code here:
        actualizarDPButton.addActionListener(e -> actualizarPerfil());
    }//GEN-LAST:event_actualizarDPButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetallesPerfil dialog = new DetallesPerfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarDPButton;
    private javax.swing.JLabel detallesPerfil;
    private javax.swing.JTextField idMembresiaTextFieldDP;
    private javax.swing.JTextField idPerfilTextFieldDP;
    private javax.swing.JLabel id_PerfilDP;
    private javax.swing.JLabel id_membresiaDP;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nickNameTextFieldDP;
    private javax.swing.JLabel nicknameDP;
    private javax.swing.JPanel panelGustos;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelPerfilDP;
    private javax.swing.JPanel panelRecomendaciones;
    private javax.swing.JPanel panelTituloDP;
    private javax.swing.JButton salirDPButton;
    private javax.swing.JTable tablaGustos;
    private javax.swing.JTable tablaHistorial;
    private javax.swing.JTable tablaRecomendaciones;
    // End of variables declaration//GEN-END:variables
}
