/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Conexiones.Conexion;
import Controller.controllerPerfil;
import Model.GustaDe;
import Model.GustaDeDAO;
import Model.Historial;
import Model.HistorialDAO;
import Model.Perfil;
import Model.PerfilDAO;
import Model.Recomendacion;
import Model.RecomendacionDAO;

import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author karin
 */
public class GestionPerfiles extends javax.swing.JFrame {
    private controllerPerfil controller;
    private DefaultTableModel modeloTabla;
    
    
    /**
     * Creates new form GestinPerfiles
     */
    public GestionPerfiles() {
        initComponents();
        modeloTabla = (DefaultTableModel) perfiles.getModel();
        
        // Configurar controlador
        try {
            Connection conn = Conexion.getCnx().getCnn();
            controller = new controllerPerfil(new PerfilDAO(conn));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al conectar: " + e.getMessage());
        }
    }
    
    private void agregarPerfil() {
        try {
            Perfil p = new Perfil(
                Integer.parseInt(idPerfilTextField.getText()),
                nickNameTextField.getText(),
                Integer.parseInt(idMembresiaTextField.getText())
            );
            if (controller.crearPerfil(p)) {
                JOptionPane.showMessageDialog(this, "Membresía agregada correctamente");
                listarPerfil();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo agregar");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Verifica los campos numéricos");
        }
    }
    
    private void eliminarPerfil() {
        try {
            int id = Integer.parseInt(idPerfilTextField.getText());
            if (controller.eliminarPerfil(id)) {
                JOptionPane.showMessageDialog(this, "Eliminado correctamente");
                listarPerfil();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el perfil");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID inválido");
        }
    }

    private void listarPerfil() {
        modeloTabla.setRowCount(0);
        for (Perfil p : controller.listarPerfil()) {
            modeloTabla.addRow(new Object[]{
                p.getId_perfil(),
                p.getNickName(),
                p.getId_membresia()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        gestionPerfiles = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        perfiles = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        listarPerfiles = new javax.swing.JButton();
        eliminarPerfil = new javax.swing.JButton();
        agregarPerfiles = new javax.swing.JButton();
        verDetallesPerfil = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        id_Perfil = new javax.swing.JLabel();
        idPerfilTextField = new javax.swing.JTextField();
        nickNameTextField = new javax.swing.JTextField();
        idMembresiaTextField = new javax.swing.JTextField();
        nickname = new javax.swing.JLabel();
        id_membresia = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 255, 205));

        jPanel2.setBackground(new java.awt.Color(247, 255, 205));

        gestionPerfiles.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        gestionPerfiles.setText("Gestión Perfiles");
        gestionPerfiles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionPerfiles)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionPerfiles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(222, 235, 181));

        perfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Perfil", "Nickname", "ID Membresía"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(perfiles);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(247, 255, 205));

        listarPerfiles.setBackground(new java.awt.Color(222, 235, 181));
        listarPerfiles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        listarPerfiles.setText("Listar");
        listarPerfiles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listarPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarPerfilesActionPerformed(evt);
            }
        });

        eliminarPerfil.setBackground(new java.awt.Color(222, 235, 181));
        eliminarPerfil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        eliminarPerfil.setText("Eliminar");
        eliminarPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPerfilActionPerformed(evt);
            }
        });

        agregarPerfiles.setBackground(new java.awt.Color(222, 235, 181));
        agregarPerfiles.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        agregarPerfiles.setText("Agregar");
        agregarPerfiles.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        agregarPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPerfilesActionPerformed(evt);
            }
        });

        verDetallesPerfil.setBackground(new java.awt.Color(222, 235, 181));
        verDetallesPerfil.setText("Ver Detalles");
        verDetallesPerfil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        verDetallesPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verDetallesPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(listarPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregarPerfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verDetallesPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listarPerfiles)
                    .addComponent(agregarPerfiles)
                    .addComponent(eliminarPerfil)
                    .addComponent(verDetallesPerfil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(222, 235, 181));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Perfil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(146, 176, 109))); // NOI18N

        id_Perfil.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_Perfil.setText("ID Perfil:");

        idPerfilTextField.setForeground(new java.awt.Color(153, 153, 153));
        idPerfilTextField.setText("ID Perfil");
        idPerfilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPerfilTextFieldActionPerformed(evt);
            }
        });

        nickNameTextField.setForeground(new java.awt.Color(153, 153, 153));
        nickNameTextField.setText("Nickname");
        nickNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nickNameTextFieldActionPerformed(evt);
            }
        });

        idMembresiaTextField.setForeground(new java.awt.Color(153, 153, 153));
        idMembresiaTextField.setText("ID Membresía");

        nickname.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nickname.setText("Nickname:");

        id_membresia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id_membresia.setText("ID Membresía:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nickname)
                    .addComponent(id_membresia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(idPerfilTextField)
                    .addComponent(nickNameTextField)
                    .addComponent(idMembresiaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_Perfil)
                    .addComponent(idPerfilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nickNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nickname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idMembresiaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_membresia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verDetallesPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verDetallesPerfilActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = perfiles.getSelectedRow();
    if (filaSeleccionada != -1) {
        try {
            int idPerfil = Integer.parseInt(perfiles.getValueAt(filaSeleccionada, 0).toString());

            PerfilDAO perfilDAO = new PerfilDAO();
            Perfil perfil = perfilDAO.obtenerPorId(idPerfil);

            if (perfil != null) {
                GustaDeDAO gustaDeDAO = new GustaDeDAO();
                List<GustaDe> gustos = gustaDeDAO.obtenerGustosPorPerfil(idPerfil);

                HistorialDAO historialDAO = new HistorialDAO();
                List<Historial> historial = historialDAO.obtenerHistorialPorPerfil(idPerfil);

                RecomendacionDAO recomendacionDAO = new RecomendacionDAO();
                List<Recomendacion> recomendaciones = recomendacionDAO.obtenerRecomendacionesPorPerfil(idPerfil);

                DetallesPerfil dialogo = new DetallesPerfil(this, true);
                dialogo.setDatosPerfil(perfil);
                dialogo.setDatosGustos(gustos);
                dialogo.setDatosHistorial(historial);
                dialogo.setDatosRecomendacion(recomendaciones);
                dialogo.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el perfil.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestionPerfiles.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona una fila para ver los detalles.");
    }
    }//GEN-LAST:event_verDetallesPerfilActionPerformed

    private void idPerfilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPerfilTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPerfilTextFieldActionPerformed

    private void nickNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nickNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nickNameTextFieldActionPerformed

    private void listarPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarPerfilesActionPerformed
        // TODO add your handling code here:
        listarPerfiles.addActionListener(e -> listarPerfil());
    }//GEN-LAST:event_listarPerfilesActionPerformed

    private void agregarPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPerfilesActionPerformed
        // TODO add your handling code here:
        agregarPerfiles.addActionListener(e -> agregarPerfil());
    }//GEN-LAST:event_agregarPerfilesActionPerformed

    private void eliminarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPerfilActionPerformed
        // TODO add your handling code here:
        eliminarPerfil.addActionListener(e -> eliminarPerfil());
    }//GEN-LAST:event_eliminarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionPerfiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionPerfiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPerfiles;
    private javax.swing.JButton eliminarPerfil;
    private javax.swing.JLabel gestionPerfiles;
    private javax.swing.JTextField idMembresiaTextField;
    private javax.swing.JTextField idPerfilTextField;
    private javax.swing.JLabel id_Perfil;
    private javax.swing.JLabel id_membresia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton listarPerfiles;
    private javax.swing.JTextField nickNameTextField;
    private javax.swing.JLabel nickname;
    private javax.swing.JTable perfiles;
    private javax.swing.JButton verDetallesPerfil;
    // End of variables declaration//GEN-END:variables
}
